inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

Style/FormatStringToken:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma


AllCops:
  TargetRubyVersion: 3.0
  DisabledByDefault: false
  SuggestExtensions: true
  NewCops: enable

Performance:
  Exclude:
    - 'spec/**/*'

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

# Sometimes duplicate branches in a switch statement make the code easier to read
Lint/DuplicateBranch:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 11

# Rspec cops

RSpec/ExampleLength:
  Max: 9

RSpec/MultipleExpectations:
  Enabled: false

# Many jsonpath queries have results without a strict order defined.
# Accomodate this by using Rspec.match_array to test result arrays without requiring any specific order.
# This cop suggests using an alternative matcher that is order-specific.
RSpec/MatchArray:
  Enabled: false

# Allow rspec test module blocks to be long
Metrics/ModuleLength:
  Exclude:
    - spec/**/*
