inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

Style/FormatStringToken:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma


AllCops:
  TargetRubyVersion: 3.4
  DisabledByDefault: false
  SuggestExtensions: true
  NewCops: enable

Performance:
  Exclude:
    - 'spec/**/*'

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
