inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

Style/FormatStringToken:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma


AllCops:
  TargetRubyVersion: 3.4
  DisabledByDefault: false
  SuggestExtensions: true
  NewCops: enable

Performance:
  Exclude:
    - 'spec/**/*'

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

# Sometimes duplicate branches in a switch statement make the code easier to read
Lint/DuplicateBranch:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

# Rspec cops

RSpec/ExampleLength:
  Max: 7

# Many jsonpath queries have results without a strict order defined.
# Accomodate this by using Rspec.match_array to test result arrays without requiring any specific order.
# This cop suggests using an alternative matcher that is order-specific.
RSpec/MatchArray:
  Enabled: false

# Allow rspec test module blocks to be long
Metrics/ModuleLength:
  Exclude:
    - spec/**/*
