# frozen_string_literal: true

module Janeway
  module AST
    # Syntactically, a JSONPath query consists of a root identifier ($),
    # which stands for a nodelist that contains the root node of the
    # query argument, followed by a possibly empty sequence of segments.
    class Query
      attr_accessor :root

      # Use this Query to search the input, and return the results.
      #
      # @param input [Object] ruby object to be searched
      # @return [Array] all matched objects
      def find_all(object)
        Janeway::Interpreter.new(input).interpret(self)
      end

      def to_s
        @root.to_s
      end

      # Queries are considered equal if their ASTs evaluate to the same JSONPath string.
      #
      # The string output is generated by the AST and should be considered a "normalized"
      # form of the query. It may have different whitespace and parentheses than the original
      # input but will be semantically equivalent.
      def ==(other)
        to_s == other.to_s
      end

      # Print AST in tree format
      # Every AST class prints a 1-line representation of self, with children on separate lines
      def tree
        result = @root.tree(0)

        result.flatten.join("\n")
      end
    end
  end
end
