# frozen_string_literal: true

module Janeway
  module AST
    # Syntactically, a JSONPath query consists of a root identifier ($),
    # which stands for a nodelist that contains the root node of the
    # query argument, followed by a possibly empty sequence of segments.
    class Query
      # @return [AST::RootNode]
      attr_reader :root

      # The original jsonpath query, for use in error messages
      # @return [String]
      attr_reader :jsonpath

      # @param root_node [AST::Root]
      # @param jsonpath [String]
      def initialize(root_node, jsonpath)
        raise ArgumentError, "expect root identifier, got #{root_node.inspect}" unless root_node.is_a?(RootNode)
        raise ArgumentError, "expect query string, got #{jsonpath.inspect}" unless jsonpath.is_a?(String)

        @root = root_node
        @jsonpath = jsonpath
      end

      # Use this Query to search the input, and return the results.
      #
      # @param input [Object] ruby object to be searched
      # @return [Array] all matched objects
      def find_all(input)
        Janeway::Interpreter.new(input).interpret(self)
      end

      def to_s
        @root.to_s
      end

      # Queries are considered equal if their ASTs evaluate to the same JSONPath string.
      #
      # The string output is generated by the AST and should be considered a "normalized"
      # form of the query. It may have different whitespace and parentheses than the original
      # input but will be semantically equivalent.
      def ==(other)
        to_s == other.to_s
      end

      # Print AST in tree format
      # Every AST class prints a 1-line representation of self, with children on separate lines
      def tree
        result = @root.tree(0)

        result.flatten.join("\n")
      end
    end
  end
end
